/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LynxWalletFactory } from "./LynxWalletFactory.ts";
export * as factories from "./factories/index.ts";
export { LynxWalletFactory__factory } from "./factories/LynxWalletFactory__factory.ts";
